vaadin.launch-browser=true
spring.application.name=gpiv

# Puerto donde corre la web
server.port=8081

# Datos de conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gpiv_db
spring.datasource.username=postgres
spring.datasource.password=ACA_PONE_TU_CONTRASEÑA_DE_POSTGRES
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate (Crea las tablas solo)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect